const ENVIRONMENT = 'dev' || process.env.NEXT_PUBLIC_ENVIRONMENT;
const API_URL = process.env.NEXT_PUBLIC_API_URL;
const API_KEY = process.env.NEXT_PUBLIC_API_KEY;
const ENCRYPTION_KEY = process.env.NEXT_PUBLIC_ENCRYPTION_KEY || 'default-encryption-key';
const AUTH_DOMAIN = process.env.NEXT_PUBLIC_AUTH_DOMAIN;
const PROJECT_ID = process.env.NEXT_PUBLIC_PROJECT_ID;
const STORAGE_BUCKET = process.env.NEXT_PUBLIC_STORAGE_BUCKET;
const MESSAGING_SENDER_ID = process.env.NEXT_PUBLIC_MESSAGING_SENDER_ID;
const APP_ID = process.env.NEXT_PUBLIC_APP_ID;
const MEASUREMENT_ID = process.env.NEXT_PUBLIC_MEASUREMENT_ID;
const VAPID_KEY = process.env.NEXT_PUBLIC_VAPID_KEY;

const GOOGLE_API_KEY = process.env.NEXT_PUBLIC_GOOGLE_API_KEY;
const GOOGLE_API_CALLBACK_NAME = '' || process.env.NEXT_PUBLIC_GOOGLE_API_CALLBACK_NAME;

const environmentUtil = { ENVIRONMENT, API_URL, API_KEY, ENCRYPTION_KEY, AUTH_DOMAIN, PROJECT_ID, STORAGE_BUCKET, MESSAGING_SENDER_ID, APP_ID, MEASUREMENT_ID, VAPID_KEY, GOOGLE_API_KEY, GOOGLE_API_CALLBACK_NAME }

export default environmentUtil;